/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Font;
import javax.swing.text.StyleConstants;
import java.awt.*;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyledDocument;

/**
 *
 * @author MSI
 */
public class Crear extends javax.swing.JFrame {

    private int k = 12;
    
    
    /**
     * Creates new form Crear
     */
    public Crear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        cmbTypefont = new javax.swing.JComboBox<>();
        btnCambiar = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        btnBajar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        cmbTypefont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLD", "PLAIN", "ITALIC", " " }));
        jPanel1.add(cmbTypefont, new java.awt.GridBagConstraints());

        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiar, new java.awt.GridBagConstraints());

        btnSubir.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI\\source\\repos\\Tarea2\\EditorDeTexto\\resources\\Webp.net-resizeimage.png")); // NOI18N
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubir, new java.awt.GridBagConstraints());

        btnBajar.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI\\source\\repos\\Tarea2\\EditorDeTexto\\resources\\zz.png")); // NOI18N
        btnBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBajar, new java.awt.GridBagConstraints());

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        // TODO add your handling code here:
        int n = cmbTypefont.getSelectedIndex();
        if ( n == 0){
            Font font = new Font("Bold", Font.BOLD, 12);
            jTextPane1.setFont(font);
        }
        if ( n == 1){
            Font font = new Font("Plain", Font.PLAIN, 12);
            jTextPane1.setFont(font);
        }
        if ( n == 2){
            Font font = new Font("Italic", Font.ITALIC, 12);
            jTextPane1.setFont(font);
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
        k = k-2;
         int n = cmbTypefont.getSelectedIndex();
        if ( n == 0){
            Font font = new Font("Bold", Font.BOLD, k);
            jTextPane1.setFont(font);
        }
        if ( n == 1){
            Font font = new Font("Plain", Font.PLAIN, k);
            jTextPane1.setFont(font);
        }
        if ( n == 2){
            Font font = new Font("Italic", Font.ITALIC, k);
            jTextPane1.setFont(font);
        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajarActionPerformed
        // TODO add your handling code here:
        k = k+2;
         int n = cmbTypefont.getSelectedIndex();
        if ( n == 0){
            Font font = new Font("Bold", Font.BOLD, k);
            jTextPane1.setFont(font);
        }
        if ( n == 1){
            Font font = new Font("Plain", Font.PLAIN, k);
            jTextPane1.setFont(font);
        }
        if ( n == 2){
            Font font = new Font("Italic", Font.ITALIC, k);
            jTextPane1.setFont(font);
        }
    }//GEN-LAST:event_btnBajarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
    JFileChooser archivo = new JFileChooser(System.getProperty("user.dir"));
     archivo.showSaveDialog(this);
    if (archivo.getSelectedFile() != null) {
    try (FileWriter guardado = new FileWriter(archivo.getSelectedFile())) {
    guardado.write(jTextPane1.getText());
    JOptionPane.showMessageDialog(rootPane, "El archivo fue guardado con éxito en la ruta establecida");
    }
    }
    } catch (IOException ex) {
    JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajar;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JComboBox<String> cmbTypefont;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
